name: Build Releases

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      # - name: Install Dependencies
      #   run: |
      #     pip install -r requirements-dev.txt

      - name: Build Installer
        run: |
          make build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: executable
          path: dist/roteiro/roteiro*
  
