name: Build Releases

on:
  push:
    tags:
      - 'v*':
        branches:
          - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10.x'

      - name: extract version
        id: extract_version
        run: echo "version=$(grep 'VERSION = ' src/__version__.py | cut -d'"' -f2)" >> $GITHUB_OUTPUT

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  
      - name: build execultable
        run: |
          pip install pyinstaller
          pyinstaller --onefile src/roteiro.py

      - name: upload execultable
        uses: actions/upload-artifact@v4
        with:
          name: roteiro_linux
          path: dist/roteiro

  build-win:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10.x'

      - name: extract version
        id: extract_version
        run: echo "version=$(grep 'VERSION = ' src/__version__.py | cut -d'"' -f2)" >> $GITHUB_OUTPUT

      - name: Package Application
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: src/roteiro.py
  
      - uses: actions/upload-artifact@v4
        with:
          name: roteiro_win
          path: dist/roteiro.exe

#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: '3.10.x'

#       - name: Create Release
#         id: create_release
#         uses: actions/create-release@v1
#         with:
#           tag_name: ${{ steps.extract_version.outputs.version }}
#           release_name: Release ${{ steps.extract_version.outputs.version }}
#           draft: false
#           prerelease: false

#       - name: Upload Release Artifacts
#         id: upload-release-artifacts
#         uses: actions/upload-release-asset@v1
#         with:
#           upload_url: ${{ steps.create_release.outputs.upload_url }}
#           asset_path: dist/roteiro/roteiro*
#           asset_name: roteiro*
#           asset_content_type: application/octet-stream
#           token: ${{ secrets.GITHUB_TOKEN }}
