name: Code Quality

on: [push]

jobs:

  lint:
    name: flake8 linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: run flake8
        uses: py-actions/flake8@v2
        with:
          max-line-length: "80"

  format:
    name: black formating
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: run black
        uses: psf/black@stable

  typecheck:
    name: mypy typechecking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: install mypy
        run: pip install mypy

      - name: run mypy
        run: mypy src/
